services:
  postgresql:
    image: postgres
    container_name: postgre_sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 10s

  app:
    build:
      context: ./app-api  
      dockerfile: Dockerfile  
    container_name: spring_app
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgre_sql:5432/user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: 123456
  frontend:
    build:
      context: ./app-ui  
      dockerfile: Dockerfile  
    container_name: frontend_app
    restart: always
    ports:
      - "5173:80"  
    environment:
      - VITE_API_URL=http://backend:8080  
    depends_on:
      - app

networks:
  default:
    driver: bridge
